version: "3"
services:
  db:
    image: postgres:latest
    container_name: grocery_list_db
    # restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      # - ./data:/var/lib/postgresql/data
      - /src/database/db_scripts/database.sql:/docker-entrypoint-initdb.d/rw

  db-test:
    image: postgres:latest
    container_name: grocery_list_db_test
    # restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      # - ./data:/var/lib/postgresql/data
      - /src/database/db_scripts/database.sql:/docker-entrypoint-initdb.d/rw
