version: "3"
services:
  db:
    image: postgres:latest
    container_name: grocery_list_db
    # restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - webapi_network

  grocery-list-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: grocery_list_api
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: postgres
    depends_on:
      - db
    networks:
      - webapi_network

networks:
  webapi_network:
    driver: bridge
